name: Lint

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: jdx/mise-action@5ac50f778e26fac95da98d50503682459e86d566
      - run: mise run check
      - run: mise run build
