---
name: Publish Arch fixture

# yamllint disable-line rule:truthy
on:
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  publish:
    name: Build context-git fixture
    uses: timmo001/workflows/.github/workflows/build-arch-package.yml@48c0a15d34fb2ece581278b17829dfacbe0b1462 # master
    with:
      package-name: context-git
    secrets:
      ARCH_REPO_DISPATCH_TOKEN: ${{ secrets.ARCH_REPO_DISPATCH_TOKEN }}
