---
name: Publish Arch fixture

# yamllint disable-line rule:truthy
on:
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  publish:
    name: Build context-git fixture
    uses: >- # master
      timmo001/workflows/.github/workflows/build-arch-package.yml@20ef62500d692bda529eec472ed3e31fe4bb0561
    with:
      package-name: context-git
    secrets:
      ARCH_REPO_DISPATCH_TOKEN: ${{ secrets.ARCH_REPO_DISPATCH_TOKEN }}
