---
name: Publish Arch fixture

# yamllint disable-line rule:truthy
on:
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  publish:
    name: Build context-git fixture
    uses: timmo001/workflows/.github/workflows/build-arch-package.yml@49bbe9c0795b8553b4c6cf5997406747fd42b1b7 # master
    with:
      package-name: context-git
    secrets:
      ARCH_REPO_DISPATCH_TOKEN: ${{ secrets.ARCH_REPO_DISPATCH_TOKEN }}
